spring:
  datasource:
      url: jdbc:mysql://localhost:3306/jinengshu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
mybatis:
  mapper-locations: classpath:com/example/demo/xiuzhenshu/dao/*.xml
